spring:
  application:
    name: space
server:
  port: 8888
eureka:
  instance:
    #preferIpAddress: true
    hostname: localhost
    appname: babyspace-space

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka