spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arjen0925/babyspace
          username: Arjen0925
          password: jxj223416
          default-label: master
          search-paths: config-repo
server:
  port: 8889

eureka:
  instance:
    hostname: localhost
    appname: babyspace-config
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
