spring:
  application:
    name: config
server:
  port: 8889
eureka:
  instance:
    hostname: localhost
    appname: babyspace-config

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka