spring:
  application:
    name: auth
server:
  port: 8888
#eureka:
#  instance:
#    hostname: localhost
#    appname: babyspace-auth
#
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka