server:
  port: 8761
eureka:
  instance:
    hostname: eureka-center
    appname: eureka-center
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    #evictionIntervalTimerInMs: 4000